### ISSUE TITLE
绘制时未调用cg_move_to会导致崩溃问题

### ISSUE THREAD

**Issue by zentelfong** [xboot/libcg#1]
执行如下代码，当注释掉`cg_move_to(ctx, 0, 0);`时程序运行会崩溃
`static void crash_test(const char* filename)
{
	struct cg_surface_t* surface = cg_surface_create(256, 256);
	struct cg_ctx_t* ctx = cg_create(surface);

	//cg_move_to(ctx, 0, 0);
	cg_line_to(ctx, 256.0, 256.0);

	cg_set_line_width(ctx, 10.0);
	cg_stroke(ctx);

	cg_surface_write_to_png(surface, filename);
	cg_destroy(ctx);
	cg_surface_destroy(surface);
}
`

**Comment by jianjunjiang** [comment]
这个问题不算bug，画线肯定需要指定从哪儿开始画，以及画到哪里，所以问题直接关闭了。
